# Generated by Django 5.1 on 2024-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produit', '0002_detailfacture_facture_detailfacture_facture'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
